// <auto-generated />
using System;
using AquacultureAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AquacultureAPI.Migrations
{
    [DbContext(typeof(AquacultureContext))]
    [Migration("20250930020305_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AquacultureAPI.Models.LechugaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AlturaCm")
                        .HasPrecision(10, 4)
                        .HasColumnType("float(10)");

                    b.Property<double>("AreaFoliarCm2")
                        .HasPrecision(10, 4)
                        .HasColumnType("float(10)");

                    b.Property<double>("HumedadPorcentaje")
                        .HasPrecision(10, 4)
                        .HasColumnType("float(10)");

                    b.Property<double>("TemperaturaC")
                        .HasPrecision(10, 4)
                        .HasColumnType("float(10)");

                    b.Property<int>("TiempoSegundos")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("pH")
                        .HasPrecision(10, 4)
                        .HasColumnType("float(10)");

                    b.HasKey("Id");

                    b.HasIndex("TiempoSegundos")
                        .HasDatabaseName("IX_LechugasData_TiempoSegundos");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_LechugasData_Timestamp");

                    b.ToTable("LechugasData");
                });

            modelBuilder.Entity("AquacultureAPI.Models.TruchaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ConductividadUsCm")
                        .HasPrecision(10, 4)
                        .HasColumnType("float(10)");

                    b.Property<double>("LongitudCm")
                        .HasPrecision(10, 4)
                        .HasColumnType("float(10)");

                    b.Property<double>("TemperaturaC")
                        .HasPrecision(10, 4)
                        .HasColumnType("float(10)");

                    b.Property<int>("TiempoSegundos")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("pH")
                        .HasPrecision(10, 4)
                        .HasColumnType("float(10)");

                    b.HasKey("Id");

                    b.HasIndex("TiempoSegundos")
                        .HasDatabaseName("IX_TruchasData_TiempoSegundos");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_TruchasData_Timestamp");

                    b.ToTable("TruchasData");
                });
#pragma warning restore 612, 618
        }
    }
}
